### ISSUE TITLE
MaskedArray TODO list

### ISSUE THREAD

**Issue by ahaldane** [ahaldane/ndarray_ducktypes#1]
TODO list:
 
- [ ] Complete writing tests
  - [ ] tests for parsing input with X values (mixtures of ndarrays, X, scalars)
  - [ ] tests for each npy-api method
- [ ] Finish npy-api functions still planned for implementation
  - [ ] np.cov, np.correlate
  - [ ] np.einsum_path
  - [ ] np.apply_along_axis, np.apply_over_axes
  - [ ] np.rot90
  - [ ] np.fliplr, np.flipud
  - [ ] np.pad (? may be too much effort to implement)
  - [ ] np.piecewise
  - [ ] np.ediff1d, np.gradient
  - [ ] np.unwrap 
 - [ ] Planning for future configurability: How to provide optional SKIPNA mask style? How to give optional ufunc auto-mask-invalid behavior. Should it be by MaskedArray factory? submodule? configuration method?

Possible further npy-api methods to implement:     np.is_busday, np.busday_offset, np.busday_count, np.datetime_as_string, np.asfarray, np.vander, np.tril_indices_from, np.triu_indices_from, np.sort_complex, np.trim_zeros, np.i0, np.msort, np.trapz, np.ix_, np.fill_diagonal, np.diag_indices_from, np.lib.scimath.sqrt, np.lib.scimath.log, np.lib.scimath.log10, np.lib.scimath.logn, np.lib.scimath.log2, np.lib.scimath.power, np.lib.scimath.arccos, np.lib.scimath.arcsin, np.lib.scimath.arctanh, np.poly, np.roots, np.polyint, np.polyder, np.polyfit, np.polyval, np.polyadd, np.polysub, np.polymul, np.polydiv, np.intersect1d, np.setxor1d, np.in1d, np.isin, np.union1d, np.setdiff1d, np.fv, np.pmt, np.nper, np.ipmt, np.ppmt, np.pv, np.rate, np.irr, np.npv, np.mirr, np.save, np.savez, np.savez_compressed, np.savetxt,

**Comment by ahaldane** [comment]
Numpy-API implementations for MaskedArray which have/need tests:

 * [ ] np.all
 * [ ] np.any
 * [ ] np.amax
 * [ ] np.max
 * [ ] np.argmax
 * [ ] np.amin
 * [ ] np.min
 * [ ] np.argmin
 * [ ] np.sort
 * [ ] np.argsort
 * [ ] np.partition
 * [ ] np.argpartition
 * [ ] np.searchsorted
 * [ ] np.digitize
 * [ ] np.lexsort
 * [ ] np.mean
 * [ ] np.var
 * [ ] np.std
 * [ ] np.average
 * [ ] np.median
 * [ ] np.percentile
 * [ ] np.quantile
 * [ ] np.cov
 * [ ] np.corrcoef
 * [ ] np.clip
 * [ ] np.compress
 * [ ] np.copy
 * [ ] np.prod
 * [ ] np.product
 * [ ] np.cumprod
 * [ ] np.cumproduct
 * [ ] np.sum
 * [ ] np.cumsum
 * [ ] np.diagonal
 * [ ] np.diag
 * [ ] np.diagflat
 * [ ] np.tril
 * [ ] np.triu
 * [ ] np.trace
 * [ ] np.dot
 * [ ] np.vdot
 * [ ] np.cross
 * [ ] np.inner
 * [ ] np.outer
 * [ ] np.kron
 * [ ] np.tensordot
 * [ ] np.einsum
 * [ ] (np.einsum_path
 * [ ] np.correlate
 * [ ] np.convolve
 * [ ] np.real
 * [ ] np.imag
 * [ ] np.ptp
 * [ ] np.take
 * [ ] np.put
 * [ ] np.take_along_axis
 * [ ] np.put_along_axis
 * [ ] np.apply_along_axis
 * [ ] np.apply_over_axes
 * [ ] np.ravel
 * [ ] np.repeat
 * [ ] np.reshape
 * [ ] np.resize
 * [ ] np.meshgrid
 * [ ] np.around
 * [ ] np.round
 * [ ] np.fix
 * [ ] np.squeeze
 * [ ] np.swapaxes
 * [ ] np.transpose
 * [ ] np.roll
 * [ ] np.rollaxis
 * [ ] np.moveaxis
 * [ ] np.flip
 * [ ] np.rot90
 * [ ] np.fliplr
 * [ ] np.flipud
 * [ ] np.expand_dims
 * [ ] np.concatenate
 * [ ] np.block
 * [ ] np.column_stack
 * [ ] np.dstack
 * [ ] np.vstack
 * [ ] np.hstack
 * [ ] np.array_split
 * [ ] np.split
 * [ ] np.hsplit
 * [ ] np.vsplit
 * [ ] np.dsplit
 * [ ] np.tile
 * [ ] np.atleast_1d
 * [ ] np.atleast_2d
 * [ ] np.atleast_3d
 * [ ] np.stack
 * [ ] np.delete
 * [ ] np.insert
 * [ ] np.append
 * [ ] np.extract
 * [ ] np.place
 * [ ] (np.pad
 * [ ] np.broadcast_to
 * [ ] np.broadcast_arrays
 * [ ] np.empty_like
 * [ ] np.ones_like
 * [ ] np.zeros_like
 * [ ] np.full_like
 * [ ] np.where
 * [ ] np.argwhere
 * [ ] np.choose
 * [ ] np.piecewise
 * [ ] np.select
 * [ ] np.unique
 * [ ] np.can_cast
 * [ ] np.min_scalar_type
 * [ ] np.result_type
 * [ ] np.common_type
 * [ ] np.bincount
 * [ ] np.count_nonzero
 * [ ] np.nonzero
 * [ ] np.flatnonzero
 * [ ] np.histogram
 * [ ] np.histogram2d
 * [ ] np.histogramdd
 * [ ] np.histogram_bin_edges
 * [ ] np.diff
 * [ ] np.interp
 * [ ] np.ediff1d
 * [ ] np.gradient
 * [ ] np.array2string
 * [ ] np.array_repr
 * [ ] np.array_str
 * [ ] np.shape
 * [ ] np.alen
 * [ ] np.ndim
 * [ ] np.size
 * [ ] np.copyto
 * [ ] np.putmask
 * [ ] np.packbits
 * [ ] np.unpackbits
 * [ ] np.isposinf
 * [ ] np.isneginf
 * [ ] np.iscomplex
 * [ ] np.isreal
 * [ ] np.iscomplexobj
 * [ ] np.isrealobj
 * [ ] np.nan_to_num
 * [ ] np.real_if_close
 * [ ] np.isclose
 * [ ] np.allclose
 * [ ] np.array_equal
 * [ ] np.array_equiv
 * [ ] np.sometrue
 * [ ] np.alltrue
 * [ ] np.angle
 * [ ] np.sinc
 * [ ] np.unwrap
